### ISSUE TITLE
ConstraintViolationProblem does not provide suitable exception message

### ISSUE THREAD

**Issue by tkrop** [zalando/problem-spring-web#67] opened 2016-10-11 15:52 UTC
**As** developer
**I want** my constrains to be in the exception message
**So that I** can see the violated constraints in the exception output without debugging.

**Comment by whiskeysierra** [comment] 2016-10-11 20:24
I'm assuming this only applies to cases where `ConstraintViolationProblem` is received and deserialized. Since it's not meant to be deserialized into its class, it would be of type `ThrowableProblem` who's [`getMessage`](https://github.com/zalando/problem/blob/master/problem/src/main/java/org/zalando/problem/ThrowableProblem.java#L29) defaults to:

```java
    @Override
    public String getMessage() {
        return Stream.of(getTitle(), getDetail())
            .filter(Objects::nonNull)
            .collect(joining(": "));
    }
```

If we actually want the message to contain all violations (not totally convinced) we'd need to add it there.

**Comment by whiskeysierra** [comment] 2016-10-13 09:00
I'm closing this, because the issue is in the wrong project.

**Comment by tkrop** [comment] 2016-10-14 07:25
Its in the first place the problem of ConstraintViolationProblem as it shows no usable information in the exception message/stack traces. If you are convinced that the parent class should handle this you can delegate this issue, but it is currently more than annoying to have to debug and dig deep into the object tree to find the interesting information.

**Comment by whiskeysierra** [comment] 2016-10-14 07:31
> Its in the first place the problem of ConstraintViolationProblem as it shows no usable information in the exception message/stack traces.

I disagree. Since you shouldn't be deserializing it, it's not an issue with ConstraintViolationProblem per se.

> but it is currently more than annoying to have to debug and dig deep into the object tree to find the interesting information.

That is not unique to ConstraintViolationProblem. E.g. ConstraintViolationException from the Bean Validation API has the same concept. The exception itself contains a rather generic message (with a clear semantic though), while the details have to be examined by inspecting the instance.

All of this shouldn't be an issue if the whole problem is logged anyway (logbook!). Alternatively the toString implementation should give you something useful, since that will include all addition parameters (including *violations* in this case).

**Comment by whiskeysierra** [comment] 2016-10-18 09:43
I just double-checked and the current toString implementation of `DefaultProblem` will in fact embed any additional parameters. And since toString is used in printStackTrace it will include violations. See the [ProblemTest](https://github.com/zalando/problem/blob/master/problem/src/test/java/org/zalando/problem/ProblemTest.java#L149) in zalando/problem.

**Closed by whiskeysierra** 2016-10-18 09:43 UTC
